### ISSUE TITLE
ユーザのpj-marowdでのアカウント名がGoogleアカウントと同期か？

### ISSUE THREAD

**Issue by reud** [reud/pj-marowd#117]
# 調査理由
ユーザ登録時、Googleアカウント名の名前が使われるが、変更を行いたい場合、実装が必要なのかどうかを確認する。

# 予想
連携時のGoogleアカウントの名前をデフォルト名にしているだけで同期はされていない。

よって、ユーザが名前を変更したい場合は別途実装が必要になる。

**Comment by kanade9** [comment]
同期はされてない？googleの名前変えて再ログインしても変化しなかった
