### ISSUE TITLE
swaggerのコメントモデルに評価レーティングの修正

### ISSUE THREAD

**Issue by reud** [reud/pj-marowd#134]
swaggerのCommentモデルにratingを追加 typeはintegerで。

参考: 
https://swagger.io/docs/specification/data-models/data-types/

x-nullableをつけてほしい

https://www.google.com/search?sxsrf=ALeKk02QqrIUSSQ8EuXcraVN4q_X1mNY7A%3A1585804507520&ei=23SFXvWkH8aMoATGn6bADw&q=swagger+2.0+x-nullable&oq=x-nullable+swagger+&gs_lcp=CgZwc3ktYWIQARgCMgQIABAeMgYIABAIEB4yBggAEAgQHjIFCAAQzQIyBggAEAgQHjIICAAQCBAKEB46BAgjECdQmwJYmwJg9QxoAHAAeACAAWaIAZwCkgEDMi4xmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab

コード生成もしといてくれると

**Comment by reud** [comment]
class モデルにレーティングの総和、レートをつけた人の人数を追加

**Comment by kanade9** [comment]
参考　https://help.apiary.io/api_101/swagger-extensions/#x-nullable
