### ISSUE TITLE
リスト一覧ページのモックの作成

### ISSUE THREAD

**Issue by kanade9** [reud/pj-marowd#27]
~6月22日まで
ListPageという名前で作成

**Comment by kanade9** [comment]
ListPageはすでに存在していたので、ListMockという名前で作成

**Comment by reud** [comment]
あっListMock.vueを作る認識であってる？
結局使用する際は、モックにデータを当てはめて使用するので、コンポーネント名にMock入れない方がいいかも・・・？ ListPageって既に存在してましたっけ・・・？

**Comment by kanade9** [comment]
了解👌
ファイル名はListPageでもう一度やってみる

**Comment by kanade9** [comment]
これもういらないので閉じますね
