### ISSUE TITLE
Backend リファクタリング

### ISSUE THREAD

**Issue by reud** [reud/pj-marowd#94]
コード見やすくするためにファイルの切り分けなど行って欲しいです

思いついた項目はこんな感じ(順不同)

- [ ] requireをなくす
- [ ] ファイルを切り分ける(他のリポジトリだとindex.tsは中はインポートしてるだけだったりする)

**Comment by reud** [comment]
[pj-marowd/index.ts at feature/84_swagger_update · gekko-org/pj-marowd](https://github.com/gekko-org/pj-marowd/blob/feature/84_swagger_update/frontend/src/gen/index.ts)

index.tsのイメージ、参考になるかも

**Comment by kanade9** [comment]
対応終了したのでcloseします
